### PR TITLE
Fix  unwind op incorrectly remove  0 value bug

### LINKED ISSUE #166: When process  $unwind ,Mingo will remove item if it contains 0 value,
When we fixed a bug on  `contexture-mongo`.https://github.com/smartprocure/contexture-mongo/pull/107. we tried to use Mingo to create a unit test, we find this bug. 

if we have a collection 
```js
[
    { "_id" : 1, "number" : 0},
    { "_id" : 2, "number" : 1}
  ]
```
 and if we use mongo shell to process unwind aggregation we will get the following result 

``` js
[
    { "_id" : 1, "number" : 0},
    { "_id" : 2, "number" : 1}
 ]
```

However, if we use Mingo to create a mock test

```js
 result = mingo.aggregate([
    { "_id" : 1, "number" : 0},
    { "_id" : 2, "number" : 1}
  ], [ { $unwind: "$number" } ] )

```

the result  is 

```js
[
    { "_id" : 2, "number" : 1}
 ]

```

A pull request to fix this bug has been submited

### PR DESCRIPTION
**Pull request by chris110408**
Fixes #166
when the field value is 0, the original Mingo unwind will treat the value as a false value. However, This is a different behavior compared to the real mongo shell

### CODE REVIEW

**Comment by kofrasa** [comment]
Thanks for the bug report and for submitting a fix. Looking closely I think the problem lies with the [isEmpty](https://github.com/kofrasa/mingo/blob/09989f124b5d68124e6794dcec935988af1931ca/src/util.ts#L177) function. The function should change to check specifically for a string type such as;

```js
export function isEmpty(x: AnyVal): boolean {
  return (
    isNil(x) ||
    (isString(x) && !x) ||
    (x instanceof Array && x.length === 0) ||
    (isObject(x) && Object.keys(x).length === 0)
  );
}
```

`isEmpty` should only consider container types (arrays, object literals, strings) and nils. That would address this bug and avoid similar errors in the future .

File: src/operators/pipeline/unwind.ts [hunk 1]
```diff
@@ -77,7 +77,11 @@ export function $unwind(
             return format(tmp, i);
           });
         }
-      } else if (!isEmpty(value) || preserveNullAndEmptyArrays === true) {
+      } else if (
+        !isEmpty(value) ||
+        preserveNullAndEmptyArrays === true ||
+        isNumber(value)
```
Comment (kofrasa) [inline src/operators/pipeline/unwind.ts:83]: See https://github.com/kofrasa/mingo/pull/165#issuecomment-780477399

**Review by kofrasa — CHANGES_REQUESTED** [review]
See https://github.com/kofrasa/mingo/pull/165#issuecomment-780477399

File: src/operators/pipeline/unwind.ts (hunk 1 above)
Comment (kofrasa) [inline src/operators/pipeline/unwind.ts:83]: This won't be necessary with the update to `isEmpty()`

**Review by kofrasa — CHANGES_REQUESTED** [review]
See: https://github.com/kofrasa/mingo/pull/165/files#r577833503

File: src/util.ts [hunk 2]
```diff
@@ -172,9 +172,9 @@ export function truthy(arg: AnyVal): boolean {
 export function isEmpty(x: AnyVal): boolean {
```
Comment (chris110408) [inline src/util.ts:172]: isEmpty will genereate different result compare to isEmpty function of  lodash.
 _.isEmpty(0) === true

**Comment by kofrasa** [comment]
Thanks a lot for the work. Really appreciate it. The new version [4.1.2](https://github.com/kofrasa/mingo/releases/tag/4.1.2) has been published.

**Comment by chris110408** [comment]
> Thanks a lot for the work. Really appreciate it. The new version [4.1.2](https://github.com/kofrasa/mingo/releases/tag/4.1.2) has been published.

Thank you for your quick response.

File: src/util.ts (hunk 2 above)
Comment (kofrasa) [reply src/util.ts:172]: I missed this comment earlier but regardless I think we should prefer our current semantics. It is also for such discrepancies that `mingo` has no dependencies.  `0` being empty overloads the meaning of empty, although a case can be made for it. What about `false`, is that also empty. If not empty then why? 

Our current semantics make few assumptions which makes things easier to reason about IMO.
